# Generated by Django 3.0.5 on 2020-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
