# Generated by Django 3.0.5 on 2020-05-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200506_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bpi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
