# Generated by Django 3.0.5 on 2020-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200509_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bpi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
