# Generated by Django 3.0.5 on 2020-05-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sendemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='id',
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='pass_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Patient'),
        ),
    ]
